apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: skupper-proj1-project
  annotations:
    github.com/project-slug: backstage-skupper-demo/backstage-catalog
spec:
  type: ocp-project
  lifecycle: unknown
  owner: Joshua Mathianas
