kind: ConfigMap
apiVersion: v1
metadata:
  name: proj1-inventory
  namespace: backstage
data:
  inventory.yml: |
    all:
      children:
        local:
          hosts:
            proj1:
              ansible_connection: local
              namespace: skupper-proj2
              token:
                type: cert
              init:
                siteName: proj1
                enableServiceSync: 'true'
                enableConsole: 'true'
                enableFlowCollector: 'true'
              
              links:
                - host: proj1
              
        
        linked:
          hosts:
            proj1:
              ansible_connection: local
        
---
apiVersion: batch/v1
kind: Job
metadata:
  name: proj1-skupper-site-init
  namespace: backstage
spec:
  selector: {}
  template:
    metadata:
      name: proj1-skupper-site-init
    spec:
      serviceAccountName: pipeline
      containers:
        - name: skupper-ansible
          image: {{ .Values.ansible.image }}
          command:
            - ansible-playbook
            - /site-creation.yaml
            - -i
            - /workspace/source/inventory.yml
            - -e
            - vault_url=$(VAULT_URL)
          volumeMounts:
            - name: inventory
              mountPath: /workspace/source
          env:
            - name: VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-url
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-token
      volumes:
      - name: inventory
        configMap:
          name: proj1-inventory
          defaultMode: 420
      restartPolicy: Never
