kind: ConfigMap
apiVersion: v1
metadata:
  name: vmdb-inventory
  namespace: backstage
data:
  inventory.yml: |
    all:
      children:
        local:
          hosts:
            192.168.23.4:
              platform: "podman"
              init:
                siteName: vmdb
                ingressHosts:
                  - 192.168.23.4
                enableServiceSync: 'true'
              
              links:
                - host: proj1
              
          vars:
            ansible_user: cloud-user
        
        linked:
          hosts:
            proj1:
              ansible_connection: local
        
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vmdb-skupper-site-init
  namespace: backstage
  labels:
    backstage.io/kubernetes-id: skupper
spec:
  selector: {}
  template:
    metadata:
      name: vmdb-skupper-site-init
      labels:
        backstage.io/kubernetes-id: skupper
    spec:
      serviceAccountName: pipeline
      containers:
        - name: skupper-ansible
          image: {{ .Values.ansible.image }}
          command:
            - sh
            - -c
            - cp /workspace/.ssh/id_rsa /tmp/id_rsa && chmod 0400 /tmp/id_rsa && ansible-playbook /site-creation.yaml -i /workspace/source/inventory.yml -e vault_url=$(VAULT_URL) -e podman=true --private-key=/tmp/id_rsa
          volumeMounts:
            - name: inventory
              mountPath: /workspace/source
            - name: ssh
              mountPath: /workspace/.ssh/id_rsa
              subPath: id_rsa
          env:
            - name: ANSIBLE_HOST_KEY_CHECKING
              value: "False"
            - name: VAULT_URL
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-url
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault-secret
                  key: vault-token
      volumes:
      - name: inventory
        configMap:
          name: vmdb-inventory
          defaultMode: 420
      - name: ssh
        secret:
          secretName: ssh-key
          defaultMode: 256
      restartPolicy: Never
