apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
spec:
  project: default
  source:
    repoURL: 'https://github.com/mathianasj/janus-idp-gitops'
    path: charts/backstage
    targetRevision: HEAD
    helm:
      parameters:
        - name: app.baseUrl
          value: https://backstage-backstage.apps.{{ .Values.baseDomain }}
        - name: backend.baseUrl
          value: https://backstage-backstage.apps.{{ .Values.baseDomain }}
        - name: backend.cors.origin
          value: https://backstage-backstage.apps.{{ .Values.baseDomain }}
        - name: backend.reading.allow[0].host
          value: https://backstage-backstage.apps.{{ .Values.baseDomain }}
        - name: image
          value: quay.io/rhdh/rhdh-hub-rhel9:0.2
        
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: backstage
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
